version: '3'
services:
  redis-server:
    image: 'redis'
#    RESTART POLICY
    restart: always
  node-app:
#    RESTART POLICY
    restart: on-failure
    build: .
    ports:
      - "4001:8081"




